enableGlobalCache: false

enableTelemetry: 0

nodeLinker: pnp

packageExtensions:
  "@xstate/cli@*":
    peerDependencies:
      prettier: "*"
  "@xstate/tools-shared@*":
    peerDependencies:
      "@babel/core": "*"

yarnPath: .yarn/releases/yarn-4.0.0-rc.34.cjs
