enableTelemetry: 0

nodeLinker: pnp

packageExtensions:
  eslint-config-airbnb-typescript@*:
    peerDependencies:
      eslint: "*"
      eslint-plugin-import: "*"
  stylelint-config-recommended-scss@*:
    peerDependencies:
      postcss: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
