# SPDX-FileCopyrightText: 2021-2023 The Refinery Authors
#
# SPDX-License-Identifier: EPL-2.0

enableGlobalCache: false

enableTelemetry: false

nodeLinker: pnp

packageExtensions:
  "notistack@*":
    peerDependencies:
      "csstype": "*"
  "@xstate/cli@*":
    peerDependencies:
      prettier: "*"
  "@xstate/tools-shared@*":
    peerDependencies:
      "@babel/core": "*"

yarnPath: .yarn/releases/yarn-4.0.0-rc.42.cjs
