enableTelemetry: 0

nodeLinker: pnp

packageExtensions:
  "@xstate/cli@*":
    peerDependencies:
      prettier: "*"
  "@xstate/tools-shared@*":
    peerDependencies:
      "@babel/core": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.3.0.cjs
